language: go
sudo: required

go:
  - "1.14"

services:
  - docker

script:
  - make test

after_success:
  - docker build -t alarms .
  - docker tag alarms $DOCKER_USERNAME/alarms:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/alarms:latest
  - docker images